name: Backup Bangumi Data

on:
  # 注释：如果要定时执行，请解除以下部分的注释（删除掉行首的 # 即可）
  # ----- 解除这行之后的注释（不包括这行）-----
   schedule:
     - cron: "0 8 * * 1"  # 运行时间：每周一凌晨四点
  # ----- 解除这行之前的注释（不包括这行）-----
  workflow_dispatch:  # 也支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download and extract archive data
        run: |
          wget $(python utils.py) -O dump.zip --quiet
          unzip dump.zip

      - name: Set up environment variables
        run: echo "BANGUMI_ACCESS_TOKEN=${{ secrets.BANGUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: (Step 1) Fetch
        run: python fetch.py

      - name: (Step 2) Build HTML
        run: python generate_html.py
      
      - name: (Step 3) Build CSV
        run: python generate_csv.py

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: Output
          path: |
            takeout.json
            takeout.html
            takeout*.csv
